### ISSUE TITLE
Notify when someone answer

### ISSUE THREAD

**Issue by khursani8** [cyberhax/meanCTF#2]
As a user i want to know when someone answer and submit the flag.

**Comment by nazmiasri95** [comment]
Good idea! 
Will it be shown on the scoreboard page? For example: "Ali got the flag #1" 

Then when switching between contestant number 1 and 2, do it like, "Ali dah potong Abu" then when Abu scored more, "Abu dah potong Ali" :P

**Comment by shahrilamrias** [comment]
@nazmi69 why Ali? :3

**Comment by nazmiasri95** [comment]
@redemption024 Because Ali is well.. Damn why u ask such question !? ;D

**Comment by khursani8** [comment]
@nazmi69 yup, right now I only implemented 'Ali answered question ${question description}'
For when someone 'potong' someone you can create an issue ticket for that :p

@redemption024 because Ali common name when you learn malay language or refer to malay people :v
